title: CDA Staging 1
url: https://www.cda.gov.sg
favicon: /images/favicon-isomer.ico
colors:
  primary-color: "#1d63ae"
  secondary-color: "#f09c52"
  media-colors:
    - title: media-color-one
      color: "#333f4c"
    - title: media-color-two
      color: "#9a2b1f"
    - title: media-color-three
      color: "#144171"
    - title: media-color-four
      color: "#1d63ae"
    - title: media-color-five
      color: "#f09c52"
description: An Isomer site of the Singapore Government
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d1p5q5dulrl7u8.amplifyapp.com
prod: https://master.d1p5q5dulrl7u8.amplifyapp.com
facebook-pixel: ""
resources_name: news-and-events
shareicon: /images/CDA_RGBLogo_ICON_COLOUR.png
is_government: false
google_analytics_ga4: ""
linkedin-insights: ""
